ALTER TABLE kyc_verification
ADD COLUMN IF NOT EXISTS review_answer TEXT,
ADD COLUMN IF NOT EXISTS review_reject_type TEXT,
ADD COLUMN IF NOT EXISTS client_comment TEXT,
ADD COLUMN IF NOT EXISTS moderation_comment TEXT,
ADD COLUMN IF NOT EXISTS applicant_type TEXT,
ADD COLUMN IF NOT EXISTS client_user_id TEXT,
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS dob DATE,
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS country TEXT;
